#!/bin/bash
# Basic usage of lemonbar's output script
# WTFPL license

color0="#29230A"
color1="#FBAB3C"
color2="#262222"
color3="#7A471B"
color4="#F6FAD6"


Workspaces(){
  desktops=$(bspc query -D --names)
  focused=$(bspc query -D --names -d focused)
  output=""

  while IFS= read -r desktop; do

    n_nodes=$(bspc query -N -d $desktop)
    
    if [ ! -z "$n_nodes" ]; then
      if [ "$desktop" = "$focused" ]; then
        desktop="%{B$color0}%{F$color4}        ${desktop}        %{F-}%{B-}"
      else
        desktop="%{B$color0}%{F$color1}        ${desktop}        %{F-}%{B-}"
      fi
      output="${output} ${desktop}"
    fi
  done <<< "$desktops"

  echo -e "$output"
}

Memory(){
  echo -e "%{F$color2} $(free --mebi | grep Mem | awk '{print $3}') MeB%{F-}"
}

# This method takes more time
Cpu(){
  idle=$(mpstat 1 1 --dec=1 | sed '1,4d;s/.* //')
  output=$((100 - $idle))
  output=$($output | xargs printf "%.2f")

  echo -e "%{F$color2}$output%{F-}" 
}

CpuTemp(){
  temp=$(sensors | grep "Tctl" | sed "s/Tctl: *+//;s/ºC *//")

  if [ 1 -eq "$(echo "${temp:0:4} > 80" | bc)" ]; then
   echo -e "%{F#FF0000}${temp:0:6}%{F-}"
  elif [ 1 -eq "$(echo "${temp:0:4} > 60" | bc)" ]; then
   echo -e "%{F#FFA929}${temp:0:6}%{F-}"
  else
   echo -e "%{F$color2}${temp:0:6}%{F-}"
  fi

}

Clock(){
  DATE=$(date "+%d/%m/%y")
  TIME=$(date "+%Ih%Mm%Ss")
  echo -e "%{F$color2}${DATE}%{F-} %{F$color3}>>%{F-} %{F$color2}${TIME}%{F-}"
}

Uptime(){
  uptime=$(uptime | awk '{print $3}' | cut -d',' -f1 )
  echo -e "%{F$color2}Running for: $uptime%{F-}"
}

_separator(){
  echo -e "%{F$color3} >> %{F-}"
}

Update(){
  echo -e "%{l}$(Workspaces)%{B-} $(Uptime)%{r}$(Memory)$(_separator)$(CpuTemp)$(_separator)$(Clock)%{B-}"
}

while true; do
  Update
  sleep 1s &
  wait
done
